# Generated by Django 3.1.2 on 2021-06-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency_value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('cur_name', models.CharField(max_length=3)),
                ('dato', models.CharField(max_length=11)),
            ],
        ),
    ]
