# Generated by Django 3.2.4 on 2021-06-14 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Currency_value',
            new_name='CurrencyValue',
        ),
    ]
